[log]
#destination = "file" # syslog or file
destination = "syslog"
file = "some.log"
level = "debug"

[hq]
host = "192.168.30.4"
#port = 36777
cycle = 2

[defaults]
alert.repeat = "yes" # repeat alert on each cycle
alert.groups = "all" # alert all configured groups
alert.users = "all"
alert.grace.seconds = 60 # wait 60 seconds before sending another alert

[check]

[check.cpu]
#usage = "7%"
usage.pct = 2
iowait = "2%"
#iowait.pct = 15
loadavg = [0.6, 0.9, 15.0]


[check.memory]
usage.gb = 200

# also alert if usage hits these values (usage in GB)
alert.include = [210,250,300]

# also execute this command if alert is raised
alert.exec = "systemctl status NetworkManager"


[check.filesystem.home]
path = "/home"
usage.pct = 30

[check.filesystem.root]
path = "/"
usage = "5gb"