[log]
#destination = "file" # syslog or file
destination = "syslog"
file = "some.log"
level = "debug"

[hq]
enabled = false
host = "192.168.30.4"
#port = 36777


[defaults]
cycle = 3
include.checks = "/tmp/*.toml"

[alert]
[alert.email]
smtp.server = "myhost"
smtp.port = 25
send.to = "users@company.com"
send.cc = "additional@company.com"
send.from = "jane@company.com"



[check]

[check.cpu]
#usage = "7%"
usage.pct = 2
iowait = "2%"
#iowait.pct = 15
loadavg = [0.6, 0.9, 15.0]


[check.memory]
usage.mb = [10,20,30]
tag = "memory"
# also alert if usage hits these values (usage in GB)

# also execute this command if alert is raised
alert.exec = "systemctl status NetworkManager"


[check.filesystem.home]
path = "/home"
usage.pct = [80,84,90]
#usage.gb = [145,146,200]

[check.filesystem.root]
path = "/"
usage = "5gb"

[check.file.testdir]
path = "/tmp/testdir"

[check.network.interface.em1]
name = "em1 iface"


#[check.network.connection.mars]
##name = "sample nc test"
#address = "mars"
#port = 22
#tag = "trading"

[check.network.connection.phoebe]
address = "192.168.40.23"
port = 2660

[check.network.bandwidth.atlas]
# requires iperf3 to be installed both on local host and remote host (remote host should have iperf3 running)
# iperf3 will run locally for the duraction of Jane cycle - 1, ie if jane cycle = 5 seconds, iperf3 will run for 4 seconds.
name = "check bandwidth to atlas"
address = "atlas"
#port = 5321 # if port not provided, default iperf3 port 5201 will be used.
limit.mbps = 20
tag = ["trading", "network"]

[check.process.slack]
#bin = "docker"
match = "/usr/bin/slack"

[check.process.gvfsd]
match = "/usr/libexec/gvfsd"
bin = "gvfsd"
#pidfile = "ddd"

[check.process.nginx]
pidfile = "/var/run/nginx.pid"

[check.process.myapp]
match = ".*myapp\\.sh"

[check.process.zed]
bin = "zed-editor"  # binary name to search
#match = "*zed-editor*"

[check.process.sshd]
match = "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"
#match = "*/usr/sbin/sshd*"
tag = "process"

[check.file.hosts]
path = "/etc/hosts"
user = "root"
group = "root"
mode = "7550"

[check.file.nonexistent]
path = "/opt/fakefile"
user = "jsmith"
